// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryApi.Models;

#nullable disable

namespace SalaryApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231110063321_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalaryApi.Models.Salary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Allowance")
                        .HasColumnType("bigint");

                    b.Property<long>("BasicSalary")
                        .HasColumnType("bigint");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Transportation")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Salary");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3706b853-57f2-4f54-be81-56011fa4393d"),
                            Allowance = 300000L,
                            BasicSalary = 10000000L,
                            Date = "14020801",
                            EmployeeId = 100L,
                            FirstName = "Ali",
                            LastName = "Ahmadi",
                            Transportation = 500000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
