// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryApi.Models;

#nullable disable

namespace SalaryApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231110164325_add index on salary")]
    partial class addindexonsalary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalaryApi.Models.Salary", b =>
                {
                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Allowance")
                        .HasColumnType("bigint");

                    b.Property<long>("BasicSalary")
                        .HasColumnType("bigint");

                    b.Property<long>("ComputedSalary")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Transportation")
                        .HasColumnType("bigint");

                    b.HasKey("EmployeeId", "Date");

                    b.HasIndex("EmployeeId", "Date");

                    b.ToTable("Salary");

                    b.HasData(
                        new
                        {
                            EmployeeId = 100L,
                            Date = "14020801",
                            Allowance = 300000L,
                            BasicSalary = 10000000L,
                            ComputedSalary = 0L,
                            FirstName = "Ali",
                            LastName = "Ahmadi",
                            Transportation = 500000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
